### ISSUE TITLE
Prefill text in Facebook share dialog?

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#100]

**Comment by adriaandotcom** [comment]
I would remove Facebook (it's not privacy friendly). This could be used if you agree:

```html
<div class="share-buttons" style="margin-top: 1rem;">
  <a
    style="background-color: #1877f2; padding: 0.3rem 0.5rem; color: white; text-decoration: none; border-radius: 3px;"
    target="_blank"
    href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fcoronastatus.no%2F&amp;src=sdkpreparse"
    >Share on Facebook</a
  >
</div>

```

**Comment by fossecode** [comment]
There are some advantages for us in using the Facebook-button. We did run some ads on Facebook in order to get traction, and we might do it again in the future if we come up with some insightful analysis or visualizations. The Facebook-button helps us target our main audience when running ads.

If it is ok for you, we could add a field in the config, specifying if we want to use the Facebook-button or the self-implemented one?

**Comment by adriaandotcom** [comment]
Yeah, for GDPR we would need consent, and that will be a bigger burden for people to fill in the form. I think that's required in Norway as well, but otherwise a setting would be fine. We probably need a few settings anyway.

Creates a PR for the button: https://github.com/BustByte/coronastatus/pull/174 (not with a setting yet). How would you do this setting?

**Comment by fossecode** [comment]
Lets just go with the button you created for now, and then we’ll fix the setting and GDPR-settings later 👍
